### ISSUE TITLE
CDT when looking up the recipes

### ISSUE THREAD

**Issue by jocker-il** [TechnoVisionDev/IronChest#13]
The game crashes to desktop when you enter a crafting bench and try looking up a recipe for one of the available chests like the copper or silver ones.

 It is clear to me that those ores are missing but in my opinion this is a bug of the mod - you need to either make the ores available in world generation or disable those items/recipes if the ores are not present  (unless another mod already takes care of generating them)

 alternatively - kindly please advise of mods that generate copper and silver ores,

thank you,

( @TechnoVisionDev - Are you still working on this mod ?)

[crash-2021-03-20_12.21.16-client.txt](https://github.com/TechnoVisionDev/IronChest/files/6175439/crash-2021-03-20_12.21.16-client.txt)
[crash-2021-03-20_12.30.16-client.txt](https://github.com/TechnoVisionDev/IronChest/files/6175440/crash-2021-03-20_12.30.16-client.txt)

**Comment by TechnoVisionDev** [comment]
This bug has been fixed in the upcoming 1.17.1 update
